---
abstract: 'Transform LaTeX source files to POD (Plain old documentation)'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  File::Spec: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Pod
provides:
  LaTeX::Pod:
    file: lib/LaTeX/Pod.pm
    version: 0.20_03
requires:
  Carp: 0
  Getopt::Long: 0
  LaTeX::TOM: 0
  List::MoreUtils: 0
  Params::Validate: 0
  boolean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20_03
